AWSTemplateFormatVersion: 2010-09-09
Description: "clarkp Test Instance"

Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair for EC2 instance Access.
    Type: AWS::EC2::KeyPair::KeyName
  DBName:
    Description: Name of the database.
    Type: String
  DBUsername:
    Description: Database Username.
    Type: String
  DBPassword:
    Description: Database Password.
    Type: String

Resources: 
  PostgreSQLDSM:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f2b4fc905b0bd1f1
      InstanceType: t2.large
      KeyName: !Ref KeyName
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
            DeleteOnTermination: True
      SecurityGroupIds:
      - sg-0edbc623dc87e2892
      - sg-0f0b0eb448eeccce1
      Tags:
      - Key: Name
        Value: DSM-Postgresql-96
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm 
          sudo systemctl enable amazon-ssm-agent
          sudo systemctl start amazon-ssm-agent
          yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
          yum install postgresql96 postgresql96-server -y
          /usr/pgsql-9.6/bin/postgresql96-setup initdb
          systemctl enable postgresql-9.6
          systemctl start postgresql-9.6
          sudo sed -i "s/local   all             all                                     peer/local   all             all                                     trust/g" /var/lib/pgsql/9.6/data/pg_hba.conf
          sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" /var/lib/pgsql/9.6/data/postgresql.conf
          sed -i "82 a host    ${DBName}        all         0.0.0.0/0       trust" /var/lib/pgsql/9.6/data/pg_hba.conf
          systemctl restart postgresql-9.6
          psql -U postgres <<EOF
          CREATE DATABASE ${DBName};
          CREATE USER ${DBUsername} with encrypted password '${DBPassword}';
          GRANT ALL PRIVILEGES ON DATABASE ${DBName} to ${DBUsername};
          GRANT ALL ON DATABASE ${DBName} to ${DBUsername};
          GRANT CONNECT ON DATABASE ${DBName} to ${DBUsername};
          ALTER ROLE ${DBUsername} CREATEDB CREATEROLE;
          EOF
          exit
          systemctl restart postgresql-9.6