AWSTemplateFormatVersion: 2010-09-09
Description: "clarkp Test Instance"

Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair for EC2 instance Access.
    Type: AWS::EC2::KeyPair::KeyName
  DSManager:
    Description: Download Deep Security Manager. Please provide the link of the desired version here.
    Type: String
    Default: https://files.trendmicro.com/products/deepsecurity/en/11.3/Manager-Linux-11.3.192.x64.sh
  DBAddress:
    Description: IP address of the Database. Please provide the IP address.
    Type: String
    Default: "172.16.0.0"
  

Resources: 
  EC2instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b49e0985beb75934
      InstanceType: m4.large
      KeyName: !Ref KeyName
      SecurityGroupIds:
      - sg-0edbc623dc87e2892
      - sg-0f0b0eb448eeccce1
      Tags:
      - Key: Name
        Value: DSM-OnPrem-Cloud
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm 
          systemctl enable amazon-ssm-agent
          systemctl start amazon-ssm-agent
          yum install wget unzip -y
          wget -P /home/ec2-user/ ${DSManager}
          cd /home/ec2-user
          TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
          PublicHostname=`curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-hostname`
          cat <<EOF>installdsm.properties
          AddressAndPortsScreen.ManagerAddress=$PublicHostname
          AddressAndPortsScreen.NewNode=True
          UpgradeVerificationScreen.Overwrite=False
          LicenseScreen.License.-1=AP-R9RM-92WHD-B2UR5-BV2YB-HZYM8-HYYVA
          DatabaseScreen.DatabaseType=PostgreSQL
          DatabaseScreen.Hostname=${DBAddress}
          DatabaseScreen.Transport=TCP
          DatabaseScreen.DatabaseName=dsm
          DatabaseScreen.Username=mydsm
          DatabaseScreen.Password=N0virus1!
          AddressAndPortsScreen.ManagerPort=4119
          AddressAndPortsScreen.HeartbeatPort=4120
          CredentialsScreen.Administrator.Username=master
          CredentialsScreen.Administrator.Password=N0virus1!
          CredentialsScreen.UseStrongPasswords=False
          SecurityUpdateScreen.UpdateComponents=True
          SecurityUpdateScreen.Proxy=False
          SecurityUpdateScreen.ProxyType=""
          SecurityUpdateScreen.ProxyAddress=""
          SecurityUpdateScreen.ProxyPort=""
          SecurityUpdateScreen.ProxyAuthentication="False"
          SecurityUpdateScreen.ProxyUsername=""
          SecurityUpdateScreen.ProxyPassword=""
          SoftwareUpdateScreen.UpdateSoftware=True
          SoftwareUpdateScreen.Proxy=False
          SoftwareUpdateScreen.ProxyType=""
          SoftwareUpdateScreen.ProxyAddress=""
          SoftwareUpdateScreen.ProxyPort=""
          SoftwareUpdateScreen.ProxyAuthentication="False"
          SoftwareUpdateScreen.ProxyUsername=""
          SoftwareUpdateScreen.ProxyPassword=""
          SoftwareUpdateScreen.ProxyAuthentication="False"
          RelayScreen.Install=True
          SmartProtectionNetworkScreen.EnableFeedback=False
          EOF
          dsm_name="$(ls /home/ec2-user | grep Manager-Linux)"
          chmod +x $dsm_name
          sh $dsm_name -q -console -t -Dinstall4j.language=en_US -varfile installdsm.properties
          sh $dsm_name -q -console -Dinstall4j.language=en_US -varfile installdsm.properties
          systemctl stop dsm_s
          /opt/dsm/dsm_c -action changesetting -name settings.configuration.webserviceAPIEnabled -value true
          /opt/dsm/dsm_c -action changesetting -name settings.configuration.statusMonitoringAPIEnabled -value true
          /opt/dsm/dsm_c -action changesetting -name settings.configuration.agentInitiatedActivation -value 1
          /opt/dsm/dsm_c -action changesetting -name settings.configuration.agentInitiatedActivationHostname -value true
          /opt/dsm/dsm_c -action changesetting -name settings.configuration.agentInitiatedActivationActiveHost -value 2
          /opt/dsm/dsm_c -action changesetting -name settings.configuration.allowReactivateClonedVM -value true
          /opt/dsm/dsm_c -action changesetting -name settings.configuration.allowReactivateUnknownVM -value true
          systemctl start dsm_s

