AWSTemplateFormatVersion: 2010-09-09
Description: "clarkp Test Instance"

Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair for EC2 instance Access.
    Type: AWS::EC2::KeyPair::KeyName
  AccessKey:
    Description: Group access key of C1-AS
    Type: String
    Default: 1f2f8e66-28cf-4854-9670-c0d2a86e238b
  SecretKey:
    Description: Group secret key of C1-AS
    Type: String
    Default: 46c2ef80-8626-4cfe-91f8-84fbb1971d47
  JavaAgent:
    Description: Download Java C1-AS agent link. Please provide it here.
    Type: String
    Default: https://download.immun.io/internal/java/trend_app_protect-4.1.5.jar

Resources: 
  C1ASPipeline:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f2b4fc905b0bd1f1
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
      - sg-0edbc623dc87e2892
      - sg-0f0b0eb448eeccce1
      Tags:
      - Key: Name
        Value: WebGoatJava-C1AS-Pipeline
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm 
          sudo systemctl enable amazon-ssm-agent
          sudo systemctl start amazon-ssm-agent
          sudo yum install -y java-11-openjdk-devel wget
          java -version
          cd /home/centos
          sudo mkdir WebGoat
          wget -P /home/centos/ https://github.com/WebGoat/WebGoat/releases/download/v8.0.0.M25/webgoat-server-8.0.0.M25.jar
          web_name="$(ls /home/centos | grep webgoat-server)"
          sudo cp /home/centos/$web_name /home/centos/WebGoat/webgoat-server.jar
          wget -P /home/centos/ ${JavaAgent}
          app_name="$(ls /home/centos | grep trend_app_protect)"
          sudo cp /home/centos/$app_name /home/centos/WebGoat/trend_app_protect.jar
          cd WebGoat/
          cat <<EOF>trend_app_protect.properties
          key = ${AccessKey}
          secret = ${SecretKey}
          debugMode = true
          EOF
          java -Dcom.trend.app_protect.config.file=trend_app_protect.properties -javaagent:/home/centos/WebGoat/trend_app_protect.jar -jar webgoat-server.jar --server.address=0.0.0.0