AWSTemplateFormatVersion: 2010-09-09
Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair for EC2 instance Access.
    Type: AWS::EC2::KeyPair::KeyName
    Default: clarkp-kp-ohio
  AvailabilityZone:
    Type: String
    Default: us-east-2
  NameInstance:
    Type: String
    Default: clarkp-test-instance

Resources:
  DSMinstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-006b2db4ca7e39d7d
      InstanceType: m4.large
      KeyName: !Ref KeyName
      SecurityGroupIds:
      - sg-0edbc623dc87e2892
      Tags:
      - Key: Name
        Value: !Sub ${NameInstance}-DSM

  PostgreDB:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f2b4fc905b0bd1f1
      InstanceType: t3a.medium
      KeyName: !Ref KeyName
      SecurityGroupIds:
      - sg-0edbc623dc87e2892
      Tags:
      - Key: Name
        Value: !Sub ${NameInstance}-DB
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
          sudo yum install postgresql96 postgresql96-server -y
          sudo /usr/pgsql-9.6/bin/postgresql96-setup initdb
          sudo systemctl enable postgresql-9.6
          sudo systemctl start postgresql-9.6
          sudo sed -n '/# IPv4 local connections:/a host    all             postgres        172.31.0.0/16           trust' /var/lib/pgsql/9.6/data/pg_hba.conf
          sudo sed -n "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /var/lib/pgsql/9.6/data/postgresql.conf
          sudo systemctl restart postgresql-9.6
          sudo su postgres
          psql
          CREATE DATABASE dsm;
          ALTER USER postgres with ENCRYPTED PASSWORD 'N0virus1!';
          GRANT ALL PRIVILEGES ON DATABASE "dsm" to postgres;
          GRANT CONNECT ON DATABASE "dsm" TO postgres;
          \q
          exit
          exit