Resources:
#Setup Variables
  TopicN: "DW-PI-dwErrorError"
  ID: "143631420864"

#Create a Topic
  MySNSPolicy:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "DW-PI-LE"
      TopicName: "DW-PI-dwErrorError"

#Create a Topic Policy
  MySNSTPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
          {
            "Version": "2008-10-17",
            "Id": "__default_policy_ID",
            "Statement": [
              {
                "Sid": "__default_statement_ID",
                "Effect": "Allow",
                "Principal": {
                  "AWS": "*"
                },
                "Action": [
                  "SNS:Publish",
                  "SNS:RemovePermission",
                  "SNS:SetTopicAttributes",
                  "SNS:DeleteTopic",
                  "SNS:ListSubscriptionsByTopic",
                  "SNS:GetTopicAttributes",
                  "SNS:Receive",
                  "SNS:AddPermission",
                  "SNS:Subscribe"
                ],
                "Resource": "arn:aws:sns:ap-southeast-1:{{ID}}:{{TopicN}}",
                "Condition": {
                  "StringEquals": {
                    "AWS:SourceOwner": "{{ID}}"
                  }
                }
              }
            ]
          }
      Topics:
        - !Ref MySNSPolicy
