AWSTemplateFormatVersion: 2010-09-09
Parameters:
  KeyName:
    Description: Name of an existing EC2 key pair for EC2 instance Access.
    Type: AWS::EC2::KeyPair::KeyName
    Default: dsaastraining-kp-ohio
  AvailabilityZone:
    Type: String
    Default: us-east-2
  NameInstance:
    Type: String
    Default: Wireshark-test-instance
  ShiftTag:
    Description: Select your shift
    Type: String
    AllowedValues:
    - ANZ-Shift
    - IST-Shift
    - NABU-Shift

Resources: 
  ec2instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d2c42f22e0567fb7
      InstanceType: t2.medium
      SubnetId: subnet-beb8bbd6
      KeyName: !Ref KeyName
      SecurityGroupIds:
      - sg-0edbc623dc87e2892
      Tags:
      - Key: Name
        Value: !Sub ${NameInstance}1
      - Key: Shift
        Value: !Ref ShiftTag